### ISSUE TITLE
fields.headline is not a valid hash key

### ISSUE THREAD

**Issue by bbugh** [ButterCMS/buttercms-ruby#11]
Hi 👋

There's some invalid Ruby code in a couple of places in the README. Listed is a hash key `fields.headline: 'foo bar'`, which is not valid Ruby code.

```ruby
params = { page: 1, page_size: 10, locale: 'en', preview: 1, fields.headline: 'foo bar', levels: 2 } # optional
                                                             ^^^^^^^^^^^^^^^
```

I assume from the API docs this is intended to be passed as a string like `'fields.headline' => 'foo bar'` as a string. Is that correct?

```ruby
params = { page: 1, page_size: 10, locale: 'en', preview: 1, "fields.headline" => 'foo bar', levels: 2 } # optional
```

**Comment by jakelumetta** [comment]
Hey @bbugh Ah yes - you're correct! Thanks for the note.  We will correct.
