### ISSUE TITLE
Errors in Pages Ruby Code

### ISSUE THREAD

**Issue by HamptonMakes** [ButterCMS/buttercms-ruby#16]
When I run the code below, I would expect to get a list of pages back, instead I get this error:

```
p ButterCMS::Page.all('*')
Traceback (most recent call last):
        2: from (irb):11
        1: from (irb):12:in `rescue in irb_binding'
TypeError (no implicit conversion of Symbol into Integer)
```

**Comment by HamptonMakes** [comment]
Seems to be coming from `buttercms-ruby (1.7) lib/buttercms-ruby.rb:67:in `[]'`

**Comment by HamptonMakes** [comment]
Upgraded to the latest `1.8` release and still get the same error:

```
buttercms-ruby (1.8) lib/buttercms-ruby.rb:68:in `[]'
buttercms-ruby (1.8) lib/buttercms-ruby.rb:68:in `api_request'
buttercms-ruby (1.8) lib/buttercms-ruby.rb:99:in `request'
buttercms-ruby (1.8) lib/buttercms/butter_resource.rb:53:in `find'
actionpack (6.1.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.1.3) lib/abstract_controller/base.rb:228:in `process_action'
actionpack (6.1.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
```

**Comment by jjudge** [comment]
Is `all` a supported method for `ButterCMS::Page`?

Here are some examples I'm using in an application to fetch a list of pages, and a page itself:

```
ButterCMS::Page.list('solution')
ButterCMS::Page.get('solution', params[:id])
```

By the way, thanks for Haml! Huge, huge fan of it.

**Comment by jakelumetta** [comment]
Hey @hcatlin - Yeah @jjudge is correct (thanks Jeff). You'll want to use `Page.list`: 

https://github.com/ButterCMS/buttercms-ruby#pages
https://buttercms.com/docs/api/?ruby#get-multiple-pages-(page-type)

Give that a try and let us know if you run into any issues.

**Comment by HamptonMakes** [comment]
Yeah, turns out that the `find` method does exist, but you have to pass it a single string argument
