### ISSUE TITLE
Please use semantic versioning or at least add a changelog

### ISSUE THREAD

**Issue by dansteele** [ButterCMS/buttercms-ruby#22]
Hey 👋 
The most recent update upgrades the lib from 1.9 to 2.0. As far as I can see, the only thing that has changed iscompatibilityy with Ruby 3. [Semantic versioning](https://semver.org/), which most open source libraries use, would suggest that a change from 1.9 to 2.0 involves large, breaking changes.

If for whatever reason you can't move to semver, please add a changelog so that customers like me don't need to start going through the code to try and work out what's changed between versions.

**Comment by jakelumetta** [comment]
Thanks for the feedback @dansteele !  So instead of 1.9 it would have been 1.9.1 is what you're proposing?

**Comment by HamptonMakes** [comment]
I believe he is! Patch probably would have been fine, but what's done is done.... 2.0 to the future!

**Comment by jakelumetta** [comment]
👍
