### ISSUE TITLE
ButterCMS::Post.find does not work correctly when slug includes a `#` character

### ISSUE THREAD

**Issue by dabrorius** [ButterCMS/buttercms-ruby#23]
Hello ButterCMS team,
I believe we discovered u bug regarding to `find` method. It is present in `2.0` and not present in `1.7`. I didn't test version `1.8` and `1.9` specifically but I'm pretty confident that it was introduced in `2.0` - more on that later.

## What happens?

When you run
```
ButterCMS::Post.find('#some-slug')
```
API client responds with
```
#<ButterCMS::Post:0x2af2bcb12c5c> JSON: {
  "detail": "Incorrect authentication credentials."
}
```

## What did you expect to happen?
I expected that `ButterCMS::NotFound (Not found.)` will be raised, same as for non-existent slugs that do not include a `#`

## Why does this happen?
I'm pretty sure I pinpointed the issue to [this line](https://github.com/ButterCMS/buttercms-ruby/commit/1dd4902c6ae20b6cf61b0d02a19de066d36bd101#diff-83c7f9c38eb215bedcc0f037fb03df264af155b5ee88a901d6c58592297edf5eR80).

Previously `URI.encode_www_form_component` was called, and it would encode the `#` in URL safe manner:
```
URI.encode_www_form_component('#ddff')
=> "%23ddff"
```

However it is not called any more, so the URL contains a raw `#`. When the request is made the HTTP client thinks this is beginning of the _fragment_ part of the URL. This leads it to ignore the _query_ part of the URL which includes the API key. This leads to `auth_token` param not being parsed correctly and we get the `Incorrect authentication credentials.` error back.

**Comment by jakelumetta** [comment]
Thanks @dabrorius ! You're right, that should return a NotFound.  @hcatlin any suggestion on how to deal with # or other invalid characters passed in as the slug?

That said - `#` is not a valid character in post slugs so could you strip them out on your end before calling the API in the short term?

**Comment by HamptonMakes** [comment]
@jakelumetta is there an official list of slug format rules? Like a regexp?

@dabrorius yeah, this was us at @veuelive trying to help get rid of deprecation warnings that would break this in Ruby 3.0! Was this just kind of strange data making it in or did you all use "#" named slugs with the encoding as a feature? Is the 404 important to your logic, or is rejecting it via a format error more in-line with your needs?

**Comment by jakelumetta** [comment]
@hcatlin typical slugification rules: should be lowercase alphanumeric and also supports dashes

My Favorite #Post -> my-favorite-post

**Comment by dabrorius** [comment]
Thanks for the reply! We don't use `#` in the slugs, however what we did was pass the param containing the slug from our Rails route directly to the ButterCMS API and relied on catching the `ButterCMS::NotFound` error to handle invalid slugs.

After an unrelated issue on our side, some users ended up accessing invalid routes that included `#` in the slug and that's how we caught this error. We can do the sanitation of slugs on our side but I wanted to share the issue with your team.

**Comment by jakelumetta** [comment]
Thanks @dabrorius ! Going to close this issue for now but thanks for the heads up. We may consider adding more cleaning logic to the SDK in the future.
