### ISSUE TITLE
Post.find("invalid_id") returns invalid Post

### ISSUE THREAD

**Issue by gaffneyc** [ButterCMS/buttercms-ruby#3]
This behavior changed in 1.1.2 with the switch to HTTParty. In version 1.1.1 trying to find an object that does not exist would raise a `RestClient::ResourceNotFound` exception, which was great because it was easy to catch inside of a Rails controller.

As of 1.1.2+ you get an invalid object.

```ruby
ButterCMS::Post.find("invalid_id")
# => raises RestClient::ResourceNotFound
```

```ruby
ButterCMS::Post.find("invalid_id")
=> #<ButterCMS::Post:0x3fec90b98af4> JSON: {
  "detail": "Not found."
}
```

**Comment by rogerjin12** [comment]
@gaffneyc Thanks for raising this. The current behavior is definitely not ideal. Do you think an exception is the preferred way to control flow versus, for example, the `find` method returning `nil` if the post isn't found?

Also see https://github.com/jnunemaker/httparty/issues/320

**Comment by gaffneyc** [comment]
@rogerjin12 honestly it depends on the context, in this case I knew that `find` would raise an error and we could rescue from it in our controllers. That said, I'm actually partial to how ActiveRecord does `find_by` which returns `nil` when the record does not exist and `find_by!` which raises an exception.

I've started on a pull request that I'll be pushing here shortly that raises an exception (`ButterCMS::NotFound`) and switches to net/http. It might be a good start to the discussion.
