### ISSUE TITLE
Unable to iterate over paginated ButterCMS::Content

### ISSUE THREAD

**Issue by rposborne** [ButterCMS/buttercms-ruby#9]
The ButterCMS::Content does not expose it's meta object with prevents us from being able to iterate over respective pages.

**Comment by jakelumetta** [comment]
Sorry for the delay in response @rposborne  - thanks for the note. We will take a look at this.

**Comment by jakelumetta** [comment]
@kevinjcoleman Have you into this issue? Do you have any cycles to take a look?

**Comment by jakelumetta** [comment]
@rposborne  This was resolved in https://github.com/ButterCMS/buttercms-ruby/pull/10  which introduces a `ButterCMS::Content.list` method.

https://github.com/ButterCMS/buttercms-ruby#collections

Give it a try and let us know if you have any questions!
